formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Terraform Hetzner Cloud RKE2 Infrastructure Module

  This Terraform module provisions the infrastructure foundation for an RKE2 Kubernetes cluster on Hetzner Cloud. The module creates the underlying infrastructure components needed for a highly available RKE2 cluster using embedded etcd by default, with Kubernetes applications deployed separately.

  ## Features

  - **High Availability**: Multiple control plane nodes with embedded etcd (or optional external datastore)
  - **Hetzner Cloud Integration**: Native support for Hetzner Cloud services (Load Balancer, Networking, etc.)
  - **Security**: Firewall rules, private networking, and secure access controls
  - **Infrastructure Focus**: Provisions servers, networking - applications deployed separately
  - **Cloud-Init**: Automated node provisioning and RKE2 installation
  - **Kubeconfig Export**: Automatic kubeconfig retrieval after cluster provisioning
  - **Optional External Datastore**: Support for external PostgreSQL-compatible datastore if needed

  ## Architecture

  The module creates the infrastructure foundation:
  - Hetzner Cloud private network and subnet
  - Control plane nodes (configurable count) with RKE2 server
  - Worker nodes (configurable count) with RKE2 agent
  - Load balancer for Kubernetes API server
  - Embedded etcd by default (optional external datastore support)
  - Firewall rules for secure access
  - **Note**: Kubernetes applications (cert-manager, external-dns, Rancher) are deployed separately

  ## Usage

  ```hcl
  module "rke2_cluster" {
    source = "github.com/FranMako/terraform-hetzner-rke2"

    hcloud_token = var.hcloud_token
    rke2_token   = var.rke2_token

    cluster_name = "my-rke2-cluster"

    # Control plane configuration
    cluster_server_names_cp   = ["cp-1", "cp-2", "cp-3"]
    private_ips_cp            = ["10.0.1.1", "10.0.1.2", "10.0.1.3"]
    nb_cp_additional_servers  = 2

    # Worker configuration
    cluster_server_names_worker = ["worker-1", "worker-2"]
    private_ips_workers         = ["10.0.1.11", "10.0.1.12"]
    nb_worker_servers           = 2
    worker_location             = "nbg1"

    # SSH access (disabled by default)
    ssh_allowed_ips = ["0.0.0.0/0"]

    # Optional: External datastore (uses embedded etcd if not provided)
    # datastore_endpoint = "postgres://user:password@host:5432/dbname"
  }
  ```

  ## Kubeconfig Export

  After successful deployment, the module automatically retrieves the admin kubeconfig from the first control plane node:

  - The kubeconfig is saved to the path specified by `kubeconfig_path` (default: `./kubeconfig.yaml`)
  - The `kubeconfig` output contains the kubeconfig content (sensitive value)
  - The `kubeconfig_command` output shows the manual command to retrieve kubeconfig if needed

  ```bash
  # Use the exported kubeconfig
  export KUBECONFIG=./kubeconfig.yaml
  kubectl get nodes
  ```

  ## Examples

  - [Basic Usage](./examples/basic/) - Simple RKE2 infrastructure setup

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Contributing

  Please read the contribution guidelines before submitting pull requests.

  ## License

  This module is licensed under the MIT License.

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
